import React, { useState, useMemo } from 'react';
import { Button } from './Button';
import { TextField } from './TextField';
import { FindingDetailItemDto } from './FindingsEditor';
import { calculateTokens } from './TokenEstimator';

export interface BundleComposerProps {
  findings: FindingDetailItemDto[];
  onCreateBundle: (name: string, selectedFindingIds: string[]) => Promise<void>;
  onCancel?: () => void;
  isOpen?: boolean;
}

export const BundleComposer: React.FC<BundleComposerProps> = ({
  findings,
  onCreateBundle,
  onCancel,
}) => {
  const [bundleName, setBundleName] = useState('Sprint Review & Defect Report');
  const [isSubmitting, setIsSubmitting] = useState(false);
  const [errorMsg, setErrorMsg] = useState<string | null>(null);
  const [copiedChannel, setCopiedChannel] = useState<string | null>(null);

  const selectedIds = useMemo(() => findings.map((f) => f.finding.id), [findings]);

  const totalTokens = useMemo(() => {
    return findings.reduce((sum, f) => {
      const markerComments = f.markers.map((m) => m.comment);
      const tk = calculateTokens(f.finding.image_width, f.finding.image_height, f.note.body, markerComments);
      return sum + tk.totalTokens;
    }, 0);
  }, [findings]);

  const generatedMarkdown = useMemo(() => {
    let md = `# ${bundleName || 'Untitled Bundle'}\n\n`;
    md += `*Generated by Snapdown Studio · ${findings.length} findings · ~${totalTokens.toLocaleString()} tokens*\n\n`;
    md += `---\n\n`;

    findings.forEach((f, idx) => {
      md += `## ${idx + 1}. Finding ${f.finding.id.slice(0, 8)}\n\n`;
      md += `![Screenshot](bundles/${bundleName.toLowerCase().replace(/[^a-z0-9]+/g, '-')}/item_${idx + 1}_burned.webp)\n\n`;
      md += `> **Summary**: ${f.note.body || 'No summary provided.'}\n\n`;
      if (f.markers.length > 0) {
        md += `**Observations**:\n`;
        f.markers.forEach((m) => {
          md += `- **[${m.ordinal}]** ${m.comment || `Marker ${m.ordinal} (${Math.round(m.x * 100)}%, ${Math.round(m.y * 100)}%)`}\n`;
        });
        md += `\n`;
      }
    });

    return md;
  }, [bundleName, findings, totalTokens]);

  const handleCopyMarkdown = async () => {
    try {
      await navigator.clipboard.writeText(generatedMarkdown);
      setCopiedChannel('md');
      setTimeout(() => setCopiedChannel(null), 2500);
    } catch {
      // Clipboard fallback
    }
  };

  const handleCreate = async () => {
    if (bundleName.trim().length === 0) {
      setErrorMsg('Please enter a bundle name');
      return;
    }
    if (selectedIds.length === 0) {
      setErrorMsg('Please select at least one finding');
      return;
    }

    setIsSubmitting(true);
    setErrorMsg(null);
    try {
      await onCreateBundle(bundleName.trim(), selectedIds);
    } catch (err: unknown) {
      const msg = err instanceof Error ? err.message : String(err);
      setErrorMsg(msg);
    } finally {
      setIsSubmitting(false);
    }
  };

  return (
    <div
      data-testid="bundle-composer"
      style={{
        width: '100%',
        maxWidth: '1100px',
        backgroundColor: 'var(--color-surface)',
        border: '1px solid var(--color-border)',
        borderRadius: 'var(--radius-lg)',
        boxShadow: 'var(--shadow-modal)',
        display: 'flex',
        flexDirection: 'column',
        overflow: 'hidden',
        boxSizing: 'border-box',
        maxHeight: '90vh',
      }}
    >
      {/* Modal Top Bar: Title, Input & Actions */}
      <div
        style={{
          padding: 'var(--space-3) var(--space-4)',
          borderBottom: '1px solid var(--color-border)',
          display: 'flex',
          alignItems: 'center',
          justifyContent: 'space-between',
          backgroundColor: 'var(--color-surface)',
          gap: 'var(--space-4)',
        }}
      >
        <div style={{ display: 'flex', alignItems: 'center', gap: 'var(--space-2)', flexShrink: 0 }}>
          <span style={{ fontSize: '1.2rem' }}>📦</span>
          <h2
            style={{
              margin: 0,
              fontSize: 'var(--text-base)',
              fontWeight: 800,
              color: 'var(--color-text)',
            }}
          >
            Review & Assemble Bundle
          </h2>
        </div>

        {/* Global Bundle Title Input spanning across top */}
        <div style={{ flex: 1, maxWidth: '440px', display: 'flex', alignItems: 'center', gap: 'var(--space-2)' }}>
          <label
            htmlFor="bundle-title-input"
            style={{ fontSize: 'var(--text-xs)', fontWeight: 700, whiteSpace: 'nowrap', color: 'var(--color-text-muted)' }}
          >
            Title:
          </label>
          <TextField
            id="bundle-title-input"
            value={bundleName}
            onChange={(e) => setBundleName(e.target.value)}
            placeholder="e.g. Sprint Review & Defect Report"
            style={{ height: '32px' }}
          />
        </div>

        <div style={{ display: 'flex', alignItems: 'center', gap: 'var(--space-2)', flexShrink: 0 }}>
          <span
            data-testid="bundle-token-badge"
            style={{
              fontSize: 'var(--text-xs)',
              fontFamily: 'var(--font-mono)',
              backgroundColor: 'var(--color-info-bg)',
              color: 'var(--color-info-text)',
              padding: '3px 10px',
              borderRadius: 'var(--radius-sm)',
              fontWeight: 700,
            }}
          >
            Est. Total: ~{totalTokens.toLocaleString()} tk
          </span>

          {onCancel && (
            <button
              type="button"
              data-testid="close-bundle-modal-btn"
              onClick={onCancel}
              style={{
                background: 'none',
                border: 'none',
                fontSize: '1.1rem',
                color: 'var(--color-text-muted)',
                cursor: 'pointer',
                padding: 'var(--space-1)',
              }}
            >
              ✕
            </button>
          )}
        </div>
      </div>

      {/* 2-Column Main Workspace: Left = Rendered Markdown Preview, Right = Handoff Sidebar */}
      <div
        style={{
          display: 'flex',
          flexDirection: 'row',
          flex: 1,
          overflow: 'hidden',
          minHeight: '520px',
        }}
      >
        {/* MAIN COLUMN: Rich Markdown Document Preview with Embedded Screenshots */}
        <div
          data-testid="bundle-markdown-document-preview"
          style={{
            flex: 1,
            backgroundColor: 'var(--color-surface)',
            padding: 'var(--space-6) var(--space-8)',
            overflowY: 'auto',
            display: 'flex',
            flexDirection: 'column',
            gap: 'var(--space-4)',
            fontFamily: 'var(--font-ui)',
            color: 'var(--color-text)',
            lineHeight: 1.6,
          }}
        >
          {/* Document Header in Markdown format */}
          <div>
            <h1
              style={{
                margin: '0 0 var(--space-1) 0',
                fontSize: 'var(--text-2xl)',
                fontWeight: 800,
                color: 'var(--color-text)',
                letterSpacing: '-0.02em',
              }}
            >
              # {bundleName || 'Untitled Bundle'}
            </h1>
            <p
              style={{
                margin: 0,
                fontSize: 'var(--text-xs)',
                color: 'var(--color-text-muted)',
                fontStyle: 'italic',
              }}
            >
              Generated by Snapdown Studio · {findings.length} findings · ~{totalTokens.toLocaleString()} tokens
            </p>
          </div>

          <hr style={{ border: 'none', borderTop: '1px solid var(--color-border)', margin: 'var(--space-2) 0' }} />

          {/* Rendered Findings as Markdown Sections with Embedded Images */}
          {findings.map((f, idx) => (
            <div
              key={f.finding.id}
              data-testid={`bundle-finding-section-${f.finding.id}`}
              style={{
                display: 'flex',
                flexDirection: 'column',
                gap: 'var(--space-3)',
                paddingBottom: 'var(--space-5)',
                borderBottom: idx < findings.length - 1 ? '1px dashed var(--color-border)' : 'none',
              }}
            >
              <h2
                style={{
                  margin: 0,
                  fontSize: 'var(--text-lg)',
                  fontWeight: 700,
                  color: 'var(--color-text)',
                }}
              >
                ## {idx + 1}. Finding {f.finding.id.slice(0, 8)}
              </h2>

              {/* Embedded Screenshot Image In-Flow */}
              <div
                style={{
                  width: '100%',
                  maxHeight: '380px',
                  backgroundColor: 'var(--color-surface-sunken)',
                  border: '1px solid var(--color-border)',
                  borderRadius: 'var(--radius-md)',
                  overflow: 'hidden',
                  display: 'flex',
                  alignItems: 'center',
                  justifyContent: 'center',
                  boxShadow: 'var(--shadow-sm)',
                }}
              >
                {f.imageSrc ? (
                  <img
                    src={f.imageSrc}
                    alt={`Screenshot Finding ${idx + 1}`}
                    style={{
                      maxWidth: '100%',
                      maxHeight: '380px',
                      objectFit: 'contain',
                      display: 'block',
                    }}
                  />
                ) : (
                  <div style={{ padding: 'var(--space-4)', color: 'var(--color-text-muted)', fontSize: 'var(--text-xs)' }}>
                    [Screenshot: {f.finding.image_width} × {f.finding.image_height} px]
                  </div>
                )}
              </div>

              {/* Rendered Blockquote for Summary */}
              <blockquote
                style={{
                  margin: 'var(--space-1) 0',
                  padding: 'var(--space-2) var(--space-3)',
                  backgroundColor: 'var(--color-surface-sunken)',
                  borderLeft: '4px solid var(--color-border-strong)',
                  borderRadius: '0 var(--radius-xs) var(--radius-xs) 0',
                  fontSize: 'var(--text-sm)',
                  color: 'var(--color-text)',
                }}
              >
                <strong>Summary</strong>: {f.note.body || 'No summary text provided.'}
              </blockquote>

              {/* Observations list */}
              {f.markers.length > 0 && (
                <div style={{ display: 'flex', flexDirection: 'column', gap: 'var(--space-1)' }}>
                  <span style={{ fontSize: 'var(--text-xs)', fontWeight: 700, color: 'var(--color-text)' }}>
                    Observations:
                  </span>
                  <ul
                    style={{
                      margin: 0,
                      paddingLeft: 'var(--space-4)',
                      display: 'flex',
                      flexDirection: 'column',
                      gap: '4px',
                      fontSize: 'var(--text-xs)',
                      color: 'var(--color-text-secondary)',
                    }}
                  >
                    {f.markers
                      .slice()
                      .sort((a, b) => a.ordinal - b.ordinal)
                      .map((m) => (
                        <li key={m.id} style={{ lineHeight: 1.5 }}>
                          <strong style={{ color: 'var(--color-accent)' }}>[{m.ordinal}]</strong>{' '}
                          {m.comment || `Marker observation for Step #${m.ordinal}`}
                        </li>
                      ))}
                  </ul>
                </div>
              )}
            </div>
          ))}
        </div>

        {/* SIDEBAR COLUMN: Handoff Channels & Atomic Assembly (300px) */}
        <div
          data-testid="bundle-col-sidebar"
          style={{
            width: '300px',
            minWidth: '300px',
            borderLeft: '1px solid var(--color-border)',
            padding: 'var(--space-4)',
            display: 'flex',
            flexDirection: 'column',
            justifyContent: 'space-between',
            backgroundColor: 'var(--color-surface-sunken)',
          }}
        >
          <div style={{ display: 'flex', flexDirection: 'column', gap: 'var(--space-3)' }}>
            <span style={{ fontSize: 'var(--text-2xs)', fontWeight: 700, textTransform: 'uppercase', color: 'var(--color-text-muted)' }}>
              🚀 Handoff Channels
            </span>

            {/* Channel 1: Clipboard Markdown */}
            <button
              type="button"
              data-testid="copy-markdown-channel-btn"
              onClick={handleCopyMarkdown}
              style={{
                padding: 'var(--space-2) var(--space-3)',
                backgroundColor: 'var(--color-surface)',
                border: '1px solid var(--color-border)',
                borderRadius: 'var(--radius-sm)',
                textAlign: 'left',
                cursor: 'pointer',
                display: 'flex',
                flexDirection: 'column',
                gap: '2px',
              }}
            >
              <div style={{ fontWeight: 700, fontSize: 'var(--text-xs)', color: 'var(--color-text)' }}>
                📋 Copy CommonMark
              </div>
              <div style={{ fontSize: 'var(--text-2xs)', color: 'var(--color-text-muted)' }}>
                {copiedChannel === 'md' ? '✓ Copied to clipboard!' : 'Ready to paste to Claude/ChatGPT.'}
              </div>
            </button>

            {/* Channel 2: Local MCP Bridge */}
            <div
              style={{
                padding: 'var(--space-2) var(--space-3)',
                backgroundColor: 'var(--color-surface)',
                border: '1px solid var(--color-border)',
                borderRadius: 'var(--radius-sm)',
                display: 'flex',
                flexDirection: 'column',
                gap: '2px',
              }}
            >
              <div style={{ fontWeight: 700, fontSize: 'var(--text-xs)', color: 'var(--color-text)' }}>
                🔑 Local MCP Bridge
              </div>
              <div style={{ fontSize: 'var(--text-2xs)', color: 'var(--color-text-muted)', fontFamily: 'var(--font-mono)' }}>
                snapdown-bridge (port 3849)
              </div>
            </div>

            {/* Channel 3: Unlisted Web Reader */}
            <div
              style={{
                padding: 'var(--space-2) var(--space-3)',
                backgroundColor: 'var(--color-surface)',
                border: '1px solid var(--color-border)',
                borderRadius: 'var(--radius-sm)',
                opacity: 0.6,
                display: 'flex',
                flexDirection: 'column',
                gap: '2px',
              }}
            >
              <div style={{ fontWeight: 700, fontSize: 'var(--text-xs)', color: 'var(--color-text)' }}>
                🌐 Publish Web Link
              </div>
              <div style={{ fontSize: 'var(--text-2xs)', color: 'var(--color-text-muted)' }}>
                Frozen under DEC-005.
              </div>
            </div>
          </div>

          {/* Execution Section */}
          <div style={{ display: 'flex', flexDirection: 'column', gap: 'var(--space-2)', marginTop: 'var(--space-4)' }}>
            {errorMsg && (
              <div style={{ color: 'var(--color-danger)', fontSize: 'var(--text-xs)' }}>
                {errorMsg}
              </div>
            )}
            <Button
              variant="primary"
              data-testid="assemble-save-bundle-btn"
              onClick={handleCreate}
              disabled={isSubmitting}
              style={{ width: '100%', padding: 'var(--space-3) var(--space-4)', fontWeight: 800 }}
            >
              {isSubmitting ? 'Assembling...' : 'Create Bundle'}
            </Button>
            <span style={{ fontSize: '0.65rem', color: 'var(--color-text-muted)', textAlign: 'center' }}>
              Burns markers into images and cleans up filmstrip.
            </span>
          </div>
        </div>
      </div>
    </div>
  );
};
