import React, { useState, useMemo } from 'react';
import { Button } from './Button';
import { TextField } from './TextField';
import { FindingDetailItemDto } from './FindingsEditor';
import { calculateTokens } from './TokenEstimator';

export interface BundleComposerProps {
  findings: FindingDetailItemDto[];
  onCreateBundle: (name: string, selectedFindingIds: string[]) => Promise<void>;
  onCancel?: () => void;
  isOpen?: boolean;
}

export const BundleComposer: React.FC<BundleComposerProps> = ({
  findings,
  onCreateBundle,
  onCancel,
}) => {
  const [bundleName, setBundleName] = useState('Sprint Review & Defect Report');
  const [activePreviewIndex, setActivePreviewIndex] = useState<number>(0);
  const [previewMode, setPreviewMode] = useState<'visual' | 'markdown'>('visual');
  const [isSubmitting, setIsSubmitting] = useState(false);
  const [errorMsg, setErrorMsg] = useState<string | null>(null);
  const [copiedChannel, setCopiedChannel] = useState<string | null>(null);

  const selectedIds = useMemo(() => findings.map((f) => f.finding.id), [findings]);

  const totalTokens = useMemo(() => {
    return findings.reduce((sum, f) => {
      const markerComments = f.markers.map((m) => m.comment);
      const tk = calculateTokens(f.finding.image_width, f.finding.image_height, f.note.body, markerComments);
      return sum + tk.totalTokens;
    }, 0);
  }, [findings]);

  const generatedMarkdown = useMemo(() => {
    let md = `# ${bundleName || 'Untitled Bundle'}\n\n`;
    md += `*Generated by Snapdown Studio · ${findings.length} findings · ~${totalTokens.toLocaleString()} tokens*\n\n`;
    md += `---\n\n`;

    findings.forEach((f, idx) => {
      md += `## ${idx + 1}. Finding ${f.finding.id.slice(0, 8)}\n\n`;
      md += `![Screenshot](bundles/${bundleName.toLowerCase().replace(/[^a-z0-9]+/g, '-')}/item_${idx + 1}_burned.webp)\n\n`;
      md += `> **Summary**: ${f.note.body || 'No summary provided.'}\n\n`;
      if (f.markers.length > 0) {
        md += `**Observations**:\n`;
        f.markers.forEach((m) => {
          md += `- **[${m.ordinal}]** ${m.comment || `Marker ${m.ordinal} (${Math.round(m.x * 100)}%, ${Math.round(m.y * 100)}%)`}\n`;
        });
        md += `\n`;
      }
    });

    return md;
  }, [bundleName, findings, totalTokens]);

  const handleCopyMarkdown = async () => {
    try {
      await navigator.clipboard.writeText(generatedMarkdown);
      setCopiedChannel('md');
      setTimeout(() => setCopiedChannel(null), 2500);
    } catch {
      // Clipboard fallback
    }
  };

  const handleCreate = async () => {
    if (bundleName.trim().length === 0) {
      setErrorMsg('Please enter a bundle name');
      return;
    }
    if (selectedIds.length === 0) {
      setErrorMsg('Please select at least one finding');
      return;
    }

    setIsSubmitting(true);
    setErrorMsg(null);
    try {
      await onCreateBundle(bundleName.trim(), selectedIds);
    } catch (err: unknown) {
      const msg = err instanceof Error ? err.message : String(err);
      setErrorMsg(msg);
    } finally {
      setIsSubmitting(false);
    }
  };

  return (
    <div
      data-testid="bundle-composer"
      style={{
        width: '100%',
        maxWidth: '1180px',
        backgroundColor: 'var(--color-surface)',
        border: '1px solid var(--color-border)',
        borderRadius: 'var(--radius-lg)',
        boxShadow: 'var(--shadow-modal)',
        display: 'flex',
        flexDirection: 'column',
        overflow: 'hidden',
        boxSizing: 'border-box',
        maxHeight: '90vh',
      }}
    >
      {/* Modal Header */}
      <div
        style={{
          padding: 'var(--space-3) var(--space-4)',
          borderBottom: '1px solid var(--color-border)',
          display: 'flex',
          alignItems: 'center',
          justifyContent: 'space-between',
          backgroundColor: 'var(--color-surface)',
        }}
      >
        <div style={{ display: 'flex', alignItems: 'center', gap: 'var(--space-2)' }}>
          <span style={{ fontSize: '1.1rem' }}>📦</span>
          <h2
            style={{
              margin: 0,
              fontSize: 'var(--text-base)',
              fontWeight: 700,
              color: 'var(--color-text)',
            }}
          >
            Review & Assemble Bundle
          </h2>
          <span
            data-testid="bundle-token-badge"
            style={{
              fontSize: 'var(--text-xs)',
              fontFamily: 'var(--font-mono)',
              backgroundColor: 'var(--color-info-bg)',
              color: 'var(--color-info-text)',
              padding: '2px 8px',
              borderRadius: 'var(--radius-sm)',
              fontWeight: 700,
            }}
          >
            Est. Total: ~{totalTokens.toLocaleString()} tk
          </span>
        </div>

        {onCancel && (
          <button
            type="button"
            data-testid="close-bundle-modal-btn"
            onClick={onCancel}
            style={{
              background: 'none',
              border: 'none',
              fontSize: '1rem',
              color: 'var(--color-text-muted)',
              cursor: 'pointer',
              padding: 'var(--space-1)',
            }}
          >
            ✕
          </button>
        )}
      </div>

      {/* 3-Column Modal Grid (SPEC-05 / State 4) */}
      <div
        style={{
          display: 'flex',
          flexDirection: 'row',
          flex: 1,
          overflow: 'hidden',
          minHeight: '480px',
        }}
      >
        {/* COLUMN 1: Bundle Contents List (280px) */}
        <div
          data-testid="bundle-col-1-contents"
          style={{
            width: '280px',
            minWidth: '280px',
            borderRight: '1px solid var(--color-border)',
            padding: 'var(--space-4)',
            display: 'flex',
            flexDirection: 'column',
            gap: 'var(--space-3)',
            backgroundColor: 'var(--color-surface-sunken)',
            overflowY: 'auto',
          }}
        >
          <div style={{ display: 'flex', flexDirection: 'column', gap: 'var(--space-1)' }}>
            <label
              htmlFor="bundle-title-input"
              style={{ fontSize: 'var(--text-2xs)', fontWeight: 700, textTransform: 'uppercase', color: 'var(--color-text-muted)' }}
            >
              Bundle Title
            </label>
            <TextField
              id="bundle-title-input"
              value={bundleName}
              onChange={(e) => setBundleName(e.target.value)}
              placeholder="e.g. Sprint Review & Defect Report"
            />
          </div>

          <div style={{ display: 'flex', flexDirection: 'column', gap: 'var(--space-2)' }}>
            <span style={{ fontSize: 'var(--text-2xs)', fontWeight: 700, textTransform: 'uppercase', color: 'var(--color-text-muted)' }}>
              Included Findings ({findings.length})
            </span>

            <div style={{ display: 'flex', flexDirection: 'column', gap: 'var(--space-2)' }}>
              {findings.map((f, idx) => {
                const isActive = activePreviewIndex === idx;

                return (
                  <div
                    key={f.finding.id}
                    data-testid={`bundle-finding-row-${f.finding.id}`}
                    onClick={() => setActivePreviewIndex(idx)}
                    style={{
                      display: 'flex',
                      alignItems: 'center',
                      gap: 'var(--space-2)',
                      padding: 'var(--space-2)',
                      backgroundColor: isActive ? 'var(--color-surface)' : 'transparent',
                      border: isActive ? '2px solid var(--color-accent)' : '1px solid var(--color-border)',
                      borderRadius: 'var(--radius-sm)',
                      cursor: 'pointer',
                      boxShadow: isActive ? 'var(--shadow-sm)' : 'none',
                      transition: 'all 0.15s ease',
                    }}
                  >
                    <div
                      style={{
                        width: '48px',
                        height: '34px',
                        borderRadius: 'var(--radius-xs)',
                        backgroundColor: 'var(--color-surface-sunken)',
                        overflow: 'hidden',
                        display: 'flex',
                        alignItems: 'center',
                        justifyContent: 'center',
                        flexShrink: 0,
                      }}
                    >
                      {f.imageSrc ? (
                        <img src={f.imageSrc} alt="" style={{ width: '100%', height: '100%', objectFit: 'cover' }} />
                      ) : (
                        <span style={{ fontSize: '0.6rem' }}>🖼️</span>
                      )}
                    </div>

                    <div style={{ flex: 1, minWidth: 0 }}>
                      <div
                        style={{
                          fontSize: 'var(--text-xs)',
                          fontWeight: 700,
                          color: isActive ? 'var(--color-accent)' : 'var(--color-text)',
                          overflow: 'hidden',
                          textOverflow: 'ellipsis',
                          whiteSpace: 'nowrap',
                        }}
                      >
                        {idx + 1}. {f.note.body ? f.note.body.slice(0, 24) : `Finding #${idx + 1}`}
                      </div>
                      <div style={{ fontSize: 'var(--text-2xs)', color: 'var(--color-text-muted)', fontFamily: 'var(--font-mono)' }}>
                        🟡 {f.markers.length} markers · {f.finding.image_width}×{f.finding.image_height}
                      </div>
                    </div>
                  </div>
                );
              })}
            </div>
          </div>
        </div>

        {/* COLUMN 2: Visual & Markdown Preview Area (Flex Center) */}
        <div
          data-testid="bundle-col-2-preview"
          style={{
            flex: 1,
            backgroundColor: 'var(--color-surface)',
            display: 'flex',
            flexDirection: 'column',
            overflow: 'hidden',
            minWidth: 0,
          }}
        >
          {/* View Mode Toggle Header */}
          <div
            style={{
              padding: 'var(--space-2) var(--space-4)',
              borderBottom: '1px solid var(--color-border)',
              display: 'flex',
              alignItems: 'center',
              justifyContent: 'space-between',
              backgroundColor: 'var(--color-surface)',
            }}
          >
            <div style={{ display: 'flex', gap: '4px', backgroundColor: 'var(--color-surface-sunken)', padding: '2px', borderRadius: 'var(--radius-sm)' }}>
              <button
                type="button"
                data-testid="preview-mode-visual-btn"
                onClick={() => setPreviewMode('visual')}
                style={{
                  padding: '3px 10px',
                  borderRadius: 'var(--radius-xs)',
                  border: 'none',
                  backgroundColor: previewMode === 'visual' ? 'var(--color-surface)' : 'transparent',
                  color: previewMode === 'visual' ? 'var(--color-text)' : 'var(--color-text-muted)',
                  fontSize: 'var(--text-xs)',
                  fontWeight: 700,
                  cursor: 'pointer',
                  boxShadow: previewMode === 'visual' ? 'var(--shadow-sm)' : 'none',
                }}
              >
                👁️ Visual Preview
              </button>
              <button
                type="button"
                data-testid="preview-mode-md-btn"
                onClick={() => setPreviewMode('markdown')}
                style={{
                  padding: '3px 10px',
                  borderRadius: 'var(--radius-xs)',
                  border: 'none',
                  backgroundColor: previewMode === 'markdown' ? 'var(--color-surface)' : 'transparent',
                  color: previewMode === 'markdown' ? 'var(--color-text)' : 'var(--color-text-muted)',
                  fontSize: 'var(--text-xs)',
                  fontWeight: 700,
                  cursor: 'pointer',
                  boxShadow: previewMode === 'markdown' ? 'var(--shadow-sm)' : 'none',
                }}
              >
                📝 Markdown Code
              </button>
            </div>

            <span style={{ fontSize: 'var(--text-2xs)', color: 'var(--color-text-muted)' }}>
              Viewing finding {activePreviewIndex + 1} of {findings.length}
            </span>
          </div>

          {/* Visual Document Preview Mode */}
          {previewMode === 'visual' ? (
            <div
              data-testid="bundle-visual-preview"
              style={{
                flex: 1,
                overflowY: 'auto',
                padding: 'var(--space-4)',
                display: 'flex',
                flexDirection: 'column',
                gap: 'var(--space-5)',
              }}
            >
              {findings[activePreviewIndex] ? (
                <div style={{ display: 'flex', flexDirection: 'column', gap: 'var(--space-3)' }}>
                  {/* Large Screenshot Image Preview */}
                  <div
                    style={{
                      width: '100%',
                      backgroundColor: 'var(--color-surface-sunken)',
                      border: '1px solid var(--color-border)',
                      borderRadius: 'var(--radius-md)',
                      overflow: 'hidden',
                      display: 'flex',
                      alignItems: 'center',
                      justifyContent: 'center',
                      maxHeight: '360px',
                      boxShadow: 'var(--shadow-raised)',
                    }}
                  >
                    {findings[activePreviewIndex].imageSrc ? (
                      <img
                        src={findings[activePreviewIndex].imageSrc}
                        alt={`Finding ${activePreviewIndex + 1}`}
                        style={{
                          maxWidth: '100%',
                          maxHeight: '360px',
                          objectFit: 'contain',
                          display: 'block',
                        }}
                      />
                    ) : (
                      <div style={{ padding: 'var(--space-6)', color: 'var(--color-text-muted)' }}>
                        Screenshot Image ({findings[activePreviewIndex].finding.image_width} × {findings[activePreviewIndex].finding.image_height} px)
                      </div>
                    )}
                  </div>

                  {/* Summary Callout Box */}
                  <div
                    style={{
                      padding: 'var(--space-3)',
                      backgroundColor: 'var(--color-info-bg)',
                      borderLeft: '4px solid var(--color-accent)',
                      borderRadius: 'var(--radius-xs)',
                    }}
                  >
                    <div style={{ fontSize: 'var(--text-2xs)', fontWeight: 800, color: 'var(--color-info-text)', textTransform: 'uppercase', marginBottom: '2px' }}>
                      Observation Summary
                    </div>
                    <div style={{ fontSize: 'var(--text-sm)', color: 'var(--color-text)', lineHeight: 1.5 }}>
                      {findings[activePreviewIndex].note.body || 'No summary text provided.'}
                    </div>
                  </div>

                  {/* Step Marker Observations List */}
                  {findings[activePreviewIndex].markers.length > 0 && (
                    <div style={{ display: 'flex', flexDirection: 'column', gap: 'var(--space-2)' }}>
                      <span style={{ fontSize: 'var(--text-2xs)', fontWeight: 800, textTransform: 'uppercase', color: 'var(--color-text-muted)' }}>
                        Step Marker Observations
                      </span>
                      {findings[activePreviewIndex].markers
                        .slice()
                        .sort((a, b) => a.ordinal - b.ordinal)
                        .map((m) => (
                          <div
                            key={m.id}
                            style={{
                              display: 'flex',
                              alignItems: 'center',
                              gap: 'var(--space-2)',
                              padding: 'var(--space-2) var(--space-3)',
                              backgroundColor: 'var(--color-surface-sunken)',
                              borderRadius: 'var(--radius-sm)',
                              border: '1px solid var(--color-border)',
                              fontSize: 'var(--text-xs)',
                            }}
                          >
                            <span
                              style={{
                                backgroundColor: 'var(--color-marker)',
                                color: 'var(--color-marker-text)',
                                width: '20px',
                                height: '20px',
                                borderRadius: 'var(--radius-full)',
                                display: 'inline-flex',
                                alignItems: 'center',
                                justifyContent: 'center',
                                fontWeight: 800,
                                fontSize: '0.7rem',
                                flexShrink: 0,
                              }}
                            >
                              {m.ordinal}
                            </span>
                            <span style={{ color: 'var(--color-text)', lineHeight: 1.4 }}>
                              {m.comment || `Observation for Step ${m.ordinal}`}
                            </span>
                          </div>
                        ))}
                    </div>
                  )}
                </div>
              ) : (
                <div style={{ textAlign: 'center', color: 'var(--color-text-muted)', padding: 'var(--space-6)' }}>
                  No finding selected.
                </div>
              )}
            </div>
          ) : (
            /* Markdown Code Mode */
            <div
              data-testid="bundle-col-2-markdown"
              style={{
                flex: 1,
                backgroundColor: 'var(--color-surface)',
                padding: 'var(--space-4)',
                overflowY: 'auto',
                fontFamily: 'var(--font-mono)',
                fontSize: 'var(--text-xs)',
                lineHeight: 1.6,
                color: 'var(--color-text)',
                whiteSpace: 'pre-wrap',
                wordBreak: 'break-word',
                userSelect: 'text',
              }}
            >
              {generatedMarkdown}
            </div>
          )}
        </div>

        {/* COLUMN 3: Handoff Channels & Atomic Assembly (300px) */}
        <div
          data-testid="bundle-col-3-handoff"
          style={{
            width: '300px',
            minWidth: '300px',
            borderLeft: '1px solid var(--color-border)',
            padding: 'var(--space-4)',
            display: 'flex',
            flexDirection: 'column',
            justifyContent: 'space-between',
            backgroundColor: 'var(--color-surface-sunken)',
          }}
        >
          <div style={{ display: 'flex', flexDirection: 'column', gap: 'var(--space-3)' }}>
            <span style={{ fontSize: 'var(--text-2xs)', fontWeight: 700, textTransform: 'uppercase', color: 'var(--color-text-muted)' }}>
              🚀 Handoff Channels
            </span>

            {/* Channel 1: Clipboard Markdown */}
            <button
              type="button"
              data-testid="copy-markdown-channel-btn"
              onClick={handleCopyMarkdown}
              style={{
                padding: 'var(--space-2) var(--space-3)',
                backgroundColor: 'var(--color-surface)',
                border: '1px solid var(--color-border)',
                borderRadius: 'var(--radius-sm)',
                textAlign: 'left',
                cursor: 'pointer',
                display: 'flex',
                flexDirection: 'column',
                gap: '2px',
              }}
            >
              <div style={{ fontWeight: 700, fontSize: 'var(--text-xs)', color: 'var(--color-text)' }}>
                📋 Copy CommonMark
              </div>
              <div style={{ fontSize: 'var(--text-2xs)', color: 'var(--color-text-muted)' }}>
                {copiedChannel === 'md' ? '✓ Copied to clipboard!' : 'Ready to paste to Claude/ChatGPT.'}
              </div>
            </button>

            {/* Channel 2: Local MCP Bridge */}
            <div
              style={{
                padding: 'var(--space-2) var(--space-3)',
                backgroundColor: 'var(--color-surface)',
                border: '1px solid var(--color-border)',
                borderRadius: 'var(--radius-sm)',
                display: 'flex',
                flexDirection: 'column',
                gap: '2px',
              }}
            >
              <div style={{ fontWeight: 700, fontSize: 'var(--text-xs)', color: 'var(--color-text)' }}>
                🔑 Local MCP Bridge
              </div>
              <div style={{ fontSize: 'var(--text-2xs)', color: 'var(--color-text-muted)', fontFamily: 'var(--font-mono)' }}>
                snapdown-bridge (port 3849)
              </div>
            </div>

            {/* Channel 3: Unlisted Web Reader */}
            <div
              style={{
                padding: 'var(--space-2) var(--space-3)',
                backgroundColor: 'var(--color-surface)',
                border: '1px solid var(--color-border)',
                borderRadius: 'var(--radius-sm)',
                opacity: 0.6,
                display: 'flex',
                flexDirection: 'column',
                gap: '2px',
              }}
            >
              <div style={{ fontWeight: 700, fontSize: 'var(--text-xs)', color: 'var(--color-text)' }}>
                🌐 Publish Web Link
              </div>
              <div style={{ fontSize: 'var(--text-2xs)', color: 'var(--color-text-muted)' }}>
                Frozen under DEC-005.
              </div>
            </div>
          </div>

          {/* Execution Section */}
          <div style={{ display: 'flex', flexDirection: 'column', gap: 'var(--space-2)', marginTop: 'var(--space-4)' }}>
            {errorMsg && (
              <div style={{ color: 'var(--color-danger)', fontSize: 'var(--text-xs)' }}>
                {errorMsg}
              </div>
            )}
            <Button
              variant="primary"
              data-testid="assemble-save-bundle-btn"
              onClick={handleCreate}
              disabled={isSubmitting}
              style={{ width: '100%', padding: 'var(--space-3) var(--space-4)', fontWeight: 800 }}
            >
              {isSubmitting ? 'Assembling...' : 'Create Bundle'}
            </Button>
            <span style={{ fontSize: '0.65rem', color: 'var(--color-text-muted)', textAlign: 'center' }}>
              Burns markers into images and cleans up filmstrip.
            </span>
          </div>
        </div>
      </div>
    </div>
  );
};
